- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-lower-constraints
    gate:
      queue: os-win
      jobs:
        - openstack-tox-lower-constraints
